version: '3.4'

x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PORT: ${DB_PORT}
  PAYPAL_BUSINESS_MAIL: ${MY_PAYPAL_ACCOUNT}
  HEARTBEAT_PERIOD: ${HEART_BEAT_PERIOD}

services:
  ### MY SQL ###
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  ### PAYMENT MANAGER ###
  paymentmanager:
    build:
      context: . #This is the root of the project TestMicroservizi
      dockerfile: paymentmanager/Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - mysqldb
    restart: always
    environment:
      <<: *common-variables #Common variables will be used in paymentmanager's dockerfile

  zookeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
    depends_on:
      - zookeper

volumes:
  mystorage: